# Generated by Django 4.1.1 on 2022-09-27 06:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("HelloProd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myprod",
            name="delete_able",
            field=models.BooleanField(default=True),
        ),
    ]
