# Generated by Django 4.1.1 on 2022-10-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HelloProd", "0004_alter_myprod_delete_able"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myprod",
            old_name="delete_able",
            new_name="deletable",
        ),
    ]
