# Generated by Django 4.1.1 on 2022-10-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HelloProd", "0005_rename_delete_able_myprod_deletable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myprod",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
